import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "../styles/global.scss";
import { AuthProvider } from "./auth-provider";

const poppins = Poppins({subsets:["latin"],weight: "300"})

export const metadata: Metadata = {
  title: "beautysalon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}